apiVersion: 1
contactPoints:
    - orgId: 1
      name: Telegram
      receivers:
        - uid: a48d5290-1632-4817-b83c-472efecb6938
          type: telegram
          settings:
            bottoken: 7083553047:AAFdW0IXimGUE-rlALTxbUviMdgSg75HA7E
            chatid: "-1002141029691"
            disable_notification: false
            disable_web_page_preview: false
            message: |
                {{ if gt (len .Alerts) 0 }}
                {{ range .Alerts }}
                {{ if .Labels.node_name }}
                Alertname: {{ .Labels.alertname }}
                Status: {{ .Labels.status }}
                Node name: {{ .Labels.node_name }}
                From: {{ .Labels.client_ip }}:{{ .Labels.client_port }}
                To: {{ .Labels.user }}@{{ .Labels.node_ip }}
                {{ else }}
                {{ range .Labels.SortedPairs }}
                The name of the label is {{ .Name }}, and the value is {{ .Value }}
                {{ end }}
                {{ end }}
                {{ end }}
                {{ end }}
            parse_mode: None
            protect_content: false
          disableResolveMessage: true
